GET http://localhost:3000/catalog
###

POST http://localhost:3000/login
Content-Type: application/json

{"login": "admin","password": "password"}

###

POST http://localhost:3000/catalog/delete/66  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzkzNTYzLCJsb2dpbiI6ImFkbWluIiwicGFzc3dvcmQiOiIkMmIkMDQkODJCZTk4bDJqa2JvYURkUWFCT2g5ZWRhZWNhS1djSmVBZVNNWUhZL2JQUzhQVXA3WjlSeXkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDA3NTIyNzUsImV4cCI6MTcwMDc1MjMzNX0.iaRN67Cm2OEa7qMrrRNGi0WnoaO2QqqAOfDMSVwcrVU

###

POST http://localhost:3000/catalog/update/66  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzkzNTYzLCJsb2dpbiI6ImFkbWluIiwicGFzc3dvcmQiOiIkMmIkMDQkODJCZTk4bDJqa2JvYURkUWFCT2g5ZWRhZWNhS1djSmVBZVNNWUhZL2JQUzhQVXA3WjlSeXkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDA3NTI0MDAsImV4cCI6MTcwMDc1MjQ2MH0.yqHdrJ5FUChaqB5QcHO4IwP-01Rk9uDrpg-KHP6w0-0

{"price":"69"}

###

POST http://localhost:4000/catalog/add  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywibG9naW4iOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJiJDA0JDFNSUdZZE1DNHRYZnI4T0xucVpjYk95djhKWWtKYmhoSFIzMDBNWjd2dGltdWpjR3djRmtpIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAxMDI2Nzc0LCJleHAiOjE3MDEwMjY4MzR9.qmJn5KrZKBKGUOz4JdfzAA1qAo46X8ziml2rcIOSByE

{
	"name":"test",
	"price":"420"
}


###

POST http://localhost:3000/token
Content-Type: application/json

{
	"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibG9naW4iOiJhZG1pbiIsInBhc3N3b3JkIjoiJDJiJDA0JC91M0JYVThmWFdqWTdPT3hLR3dXdk9nRGZ4NXpmVXFGQmdnYTJRNU9QWVlZb1VTL2NoYmw2Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAxNjI3NjM1fQ.Usqydo7QHVHVzwoYmMENd5YUWY3cvtONqFmllnmDcyM"
}



