POST http://localhost:3000/login
Content-Type: application/json

{"login": "admin","password": "password"}

###

POST http://localhost:3000/catalog/delete/66  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzkzNTYzLCJsb2dpbiI6ImFkbWluIiwibmFtZSI6bnVsbCwicGFzc3dvcmQiOiIkMmIkMDQkODJCZTk4bDJqa2JvYURkUWFCT2g5ZWRhZWNhS1djSmVBZVNNWUhZL2JQUzhQVXA3WjlSeXkiLCJyb2xlIjoiYWRtaW4iLCJyZWZyZXNoVG9rZW4iOm51bGwsImNyZWF0ZWRBdCI6IjIwMjMtMTEtMjJUMTg6MTk6MjQuNTY5WiIsInVwZGF0ZWRBdCI6IjIwMjMtMTEtMjJUMTg6MTk6MjQuNTY5WiIsImlhdCI6MTcwMDczNzA1NywiZXhwIjoxNzAwNzM3MDY3fQ.EQb0zJyYdHD1ZKnr9WpdWXG3Dm0M9fjCUPM-Mghfx_c"

###

POST http://localhost:3000/token
Content-Type: application/json

{
	"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzkzNTYzLCJsb2dpbiI6ImFkbWluIiwicGFzc3dvcmQiOiIkMmIkMDQkODJCZTk4bDJqa2JvYURkUWFCT2g5ZWRhZWNhS1djSmVBZVNNWUhZL2JQUzhQVXA3WjlSeXkiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDA3NDcwMDN9.gMJw-aXqnjXRZMfYXn3-OX6P2jLFjoIOabztkmgEsUg"
}



